global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9100',
      		  'services.freifunk-niersufer.de:9100',
                  'node01.freifunk-niersufer.de:9100',
                  'node02.freifunk-niersufer.de:9100',
                  'node03.freifunk-niersufer.de:9100',
                  'node04.freifunk-niersufer.de:9100', ]

  - job_name: 'hopglass'
    scheme: https
    scrape_interval: 60s
    scrape_timeout: 15s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['hopglass.freifunk-niersufer.de']

remote_write:
- url: "http://localhost:8086/api/v1/prom/write?db=prometheus"

remote_read:
- url: "http://localhost:8086/api/v1/prom/read?db=prometheus"
